backend:
  name: github
  repo: natdjerf/cms

media_folder: static/img
public_folder: img

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: Hours,
              name: hours,
              widget: string,
              hint: "As text: 10:30am to 10:00pm",
            }
          - {
              label: Hours description,
              name: hours_description,
              widget: string,
              hint: "Open daily...",
            }
          - {
              label: Open/Closed for the season,
              name: open_for_the_season,
              widget: boolean,
              default: false,
              hint: "Are we open for the season?",
            }
          - {
              label: Seasons open,
              name: seasons_open,
              widget: string,
              hint: "How many seasons we have been open with suffix ie 60th or 61st",
            }
          - {
              label: Address line 1,
              name: address_line_1,
              widget: string,
              hint: "Street number and name",
            }
          - {
              label: Address line 2,
              name: address_line_2,
              widget: string,
              hint: "City, state, zip",
            }
          - { label: Phone, name: phone, widget: string }
          - { label: Email, name: email, widget: string }
          - {
              label: Section welcome header,
              name: section_welcome_header,
              widget: string,
            }
          - {
              label: Section welcome text,
              name: section_welcome_text,
              widget: text,
            }
          - {
              label: Section food header,
              name: section_food_header,
              widget: string,
            }
          - { label: Section food text, name: section_food_text, widget: text }
          - {
              label: Section family header,
              name: section_family_header,
              widget: string,
            }
          - {
              label: Section family text,
              name: section_family_text,
              widget: text,
            }
          - {
              label: Section favorites header,
              name: section_favorites_header,
              widget: string,
            }
          - {
              label: Section favorites seafood,
              name: section_favorites_seafood,
              widget: text,
            }
          - {
              label: Section favorites griddle,
              name: section_favorites_griddle,
              widget: text,
            }
          - {
              label: Section favorites beverages,
              name: section_favorites_beverages,
              widget: text,
            }
          - {
              label: Welcome image about url,
              name: welcome_image_about_url,
              widget: image,
            }
          - {
              label: Welcome image about description,
              name: welcome_image_about_description,
              widget: text,
            }
          - {
              label: Welcome image food url,
              name: welcome_image_food_url,
              widget: image,
            }
          - {
              label: Welcome image food description,
              name: welcome_image_food_description,
              widget: text,
            }
          - {
              label: Family image 1 url,
              name: family_image_1_url,
              widget: image,
            }
          - {
              label: Family image 1 description,
              name: family_image_1_description,
              widget: text,
            }
          - {
              label: Family image 2 url,
              name: family_image_2_url,
              widget: image,
            }
          - {
              label: Family image description,
              name: family_image_2_description,
              widget: text,
            }
          - {
              label: Family image 3 url,
              name: family_image_3_url,
              widget: image,
            }
          - {
              label: Family image 3 description,
              name: family_image_3_description,
              widget: text,
            }

      - label: "Banner"
        name: "banner"
        folder: "content/banner"
        file: "content/banner.md"
        fields:
          - { label: Message, name: message, widget: string }
          - {
              label: Active,
              name: active,
              widget: boolean,
              hint: "Is banner notice active?",
            }
  - label: "Gallery"
    name: "gallery"
    folder: "content/gallery"
    create: true
    slug: "{{category}}-{{name}}"
    fields:
      - { label: Image, name: image, widget: image }
      - { label: Name, name: name, widget: string }
      - { label: Title, name: title, widget: string }
      - {
          label: Category,
          name: category,
          widget: string,
          default: "plate, store, team",
          hint: "Select one from list- plate: round food photos, store: the shop, team: family and employees",
        }
      - { label: Image url, name: image_url, widget: image }
  - label: "Menu"
    name: "menu"
    folder: "content/menu"
    file: "content/menu/item.md"
    create: true
    slug: "{{category}}-{{name}}"
    identifier-field: slug
    fields:
      - {
          label: Category,
          name: category,
          widget: string,
          default: "box, broiler, plates, baskets, sandwiches, griddle, wraps, subs, salads, sides, kids, favorites",
          hint: "Select one from list",
        }
      - { label: Name, name: name, widget: string }
      - { label: Title, name: title, widget: string, hint: "For admin page" }
      - {
          label: Price (if one size),
          name: price,
          widget: string,
          required: false,
          hint: " As number - 9.95. Fill in if one size only (ie, sandwich or basket). If multiple sizes, leave blank and fill in small/medium/large sizes.",
        }
      - {
          label: Small Price,
          name: small_price,
          required: false,
          widget: string,
          hint: "As number - 9.95",
        }
      - {
          label: Medium Price,
          name: medium_price,
          required: false,
          widget: string,
          hint: "As number - 9.95",
        }
      - {
          label: Large Price,
          name: large_price,
          required: false,
          widget: string,
          hint: "As number - 9.95",
        }
      - {
          label: Description,
          name: description,
          required: false,
          widget: string,
        }
      - {
          label: Created at,
          name: created,
          widget: datetime,
          hint: "As comma separated list, ie 'Harpoon, Corona, ...'",
        }
  - label: "Beverages"
    name: "beverages"
    folder: "content/beverages"
    file: "content/beverages/item.md"
    create: true
    slug: "{{category}}"
    identifier-field: slug
    fields:
      - {
          label: Category,
          name: category,
          widget: string,
          default: "cocktails, frozen, beer, draft, wine, liquor",
          hint: "Select one from list (lowercase) - beer includes cider, seltzer",
        }
      - {
          label: Title,
          name: title,
          widget: string,
          hint: "Category for admin page",
        }
      - {
          label: Name,
          name: Name,
          widget: string,
          hint: "Same as title and category",
        }
      - {
          label: Drinks,
          name: drinks,
          widget: string,
          hint: "As comma separated list, ie 'Harpoon, Corona, ...'",
        }
